### ISSUE TITLE
Newpipe-nightly-122 is using wrong version of newpipe (not the latest version)

### ISSUE THREAD

**Issue by fhintyd** [TeamNewPipe/NewPipe-nightly#16]
The latest newpipe version is 0.27.1 and it is released about 3 days ago. But the latest newpipe-nightly-122 (which is released yesterday) is still using newpipe  0.27.0 version.

**Comment by Stypox** [comment]
Yeah, sorry. I'm going to merge master to dev right now. The next nightly will have all the changes from 0.27.1.
