### ISSUE TITLE
Nightlies for rewrite / refactor

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe-nightly#18]
We might want to also have nightlies for the refactor branch. What do you think?

**Comment by XiangRongLin** [comment]
It should not be much effort.

But you should problably use a different signing key, since the current one is mine with my name etc.
that's the only part that would require some time, since I have no clue anymore about how to format/compress/whatever the signing key

**Comment by Stypox** [comment]
I setup a repo for nightly releases of the refactored NewPipe (i.e. the refactor branch): https://github.com/TeamNewPipe/NewPipe-refactor-nightly
