### ISSUE TITLE
No nightly for the latest PR #9562

### ISSUE THREAD

**Issue by nicoursi** [TeamNewPipe/NewPipe-nightly#3]
Four days ago the the PR 9562  has been merged but no nightly has been produced. Something went wrong?

https://github.com/TeamNewPipe/NewPipe/pull/9562

**Comment by TobiGr** [comment]
The CI builds one nightly per day. [Nightly-26](https://github.com/TeamNewPipe/NewPipe-nightly/releases/tag/nightly-26) contains that PR.
